version: '3'
 
services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-hugo-site:latest
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`shah256.dev`)"
      - "traefik.http.routers.blog.entrypoints=https"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog.loadbalancer.server.port=1313"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
