services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-hugo-site:latest
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    networks:
      - npm_network

networks:
  npm_network:
    external: true
