baseURL = "https://shah256.dev"
title = "shah256's notebook"
theme = "PaperMod"

enableGitInfo = true  # Git becomes your timekeeper

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

# Enable search (because who doesn't love Ctrl+F on steroids?)
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
DateFormat = "January 2, 2006"  # Go's weird but canonical date format
ShowLastMod = true  # 🎯 This is the money shot - shows "Updated on" text
mainSections = ["posts"]  # VIP list - only posts get past the velvet rope


[menu]
main = [
    {identifier = "posts", name = "Posts", url = "/posts/", weight = 10},
    {identifier = "cheatsheets", name = "Cheatsheets", url = "/cheatsheets/", weight = 20},
    {identifier = "about", name = "About", url = "/about/", weight = 40}
]

[params.homeInfoParams]
Title = "👋 Hello!"
Content = """
Where bits meet bytes and code comes to life.
Sharing thoughts on tech, security, and whatever else catches my compiler's attention.
"""
